  monster_id: 100046
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 7873
        }
      }
    }
  }
  level_overrides {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 7873
        }
      }
    }
  }
  status: APPROVED_AS_IS
