  monster_id: 101176
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 8789
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 939
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 920
        }
      }
    }
  }
  level_overrides {
    level: 1
    groups {
      group_type: PREEMPT
      condition {
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 8789
        }
      }
    }
  }
  status: APPROVED_WITH_CHANGES
