  monster_id: 103314
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 6744
        }
      }
    }
  }
  level_overrides {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            if_attributes_available: true
          }
          enemy_skill_id: 6744
        }
      }
    }
  }
  status: NEEDS_REAPPROVAL
