  monster_id: 1146
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 893
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 49
      }
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 894
        }
      }
    }
  }
  level_overrides {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 893
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 49
      }
      children {
        behavior {
          condition {
            use_chance: 50
          }
          enemy_skill_id: 894
        }
      }
    }
  }
  status: APPROVED_AS_IS
