  monster_id: 1246
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 3069
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3057
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 30
              }
              enemy_skill_id: 3059
            }
          }
          children {
            behavior {
              enemy_skill_id: 3060
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 69
            trigger_turn: 1
            always_trigger_above: 49
          }
          children {
            behavior {
              enemy_skill_id: 3058
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 3061
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 3068
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 3066
                }
              }
              children {
                behavior {
                  enemy_skill_id: 3062
                }
              }
            }
          }
        }
      }
    }
  }
  level_overrides {
    level: 1
    groups {
      group_type: PASSIVE
      condition {
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3069
        }
      }
    }
    groups {
      group_type: PREEMPT
      condition {
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3057
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 30
              }
              enemy_skill_id: 3059
            }
          }
          children {
            behavior {
              condition {
              }
              enemy_skill_id: 3060
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 69
            global_one_time: true
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
              }
              enemy_skill_id: 3058
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                  }
                  enemy_skill_id: 3061
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  condition {
                  }
                  enemy_skill_id: 3068
                }
              }
            }
          }
          children {
            group {
              condition {
              }
              children {
                behavior {
                  condition {
                  }
                  enemy_skill_id: 3066
                }
              }
              children {
                behavior {
                  condition {
                  }
                  enemy_skill_id: 3062
                }
              }
            }
          }
        }
      }
    }
  }
  status: APPROVED_WITH_CHANGES
