  monster_id: 1854
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 5298
        }
      }
    }
  }
  level_overrides {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 5298
        }
      }
    }
  }
  status: APPROVED_AS_IS
