  monster_id: 3528
  levels {
    level: 1
    groups {
      group_type: DEATH
      condition {
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 6388
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          enemy_skill_id: 12082
        }
      }
    }
  }
  level_overrides {
    level: 1
    groups {
      group_type: DEATH
      condition {
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 6388
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          enemy_skill_id: 12082
        }
      }
    }
  }
  status: APPROVED_AS_IS
