  monster_id: 4838
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 12312
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            repeats_every: 3
            trigger_turn: 1
            trigger_turn_end: 3
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 12315
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 12318
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 12319
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 12320
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 74
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 24
              }
              children {
                behavior {
                  enemy_skill_id: 12321
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 1
                trigger_turn_end: 4
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 12315
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 12318
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 12319
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 25
                  }
                  enemy_skill_id: 12320
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 24
            repeats_every: 3
            trigger_turn: 1
            trigger_turn_end: 3
          }
          children {
            behavior {
              enemy_skill_id: 12325
            }
          }
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
            trigger_enemies_remaining: 1
          }
          enemy_skill_id: 12324
        }
      }
    }
  }
