  monster_id: 553
  levels {
    level: 5
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            use_chance: 25
          }
          enemy_skill_id: 220
        }
      }
    }
  }
  level_overrides {
    level: 5
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
        use_chance: 25
      }
      children {
        behavior {
          enemy_skill_id: 220
        }
      }
    }
  }
  status: NEEDS_REAPPROVAL
