  monster_id: 6090
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 17349
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              enemy_skill_id: 17350
            }
          }
          children {
            behavior {
              enemy_skill_id: 17351
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 17353
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 17352
                }
              }
            }
          }
        }
      }
    }
  }
  level_overrides {
    level: 1
    groups {
      group_type: PREEMPT
      condition {
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 17349
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
              }
              enemy_skill_id: 17350
            }
          }
          children {
            behavior {
              condition {
              }
              enemy_skill_id: 17351
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                  }
                  enemy_skill_id: 17353
                }
              }
            }
          }
          children {
            group {
              condition {
              }
              children {
                behavior {
                  condition {
                  }
                  enemy_skill_id: 17352
                }
              }
            }
          }
        }
      }
    }
  }
  status: APPROVED_WITH_CHANGES
