  monster_id: 814
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 744
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 2
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 747
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 748
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 4
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 745
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 5
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 747
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 6
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 748
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 7
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 745
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 8
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 747
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 9
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 748
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 10
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 745
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 11
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 744
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                always_trigger_above: 49
              }
              children {
                behavior {
                  enemy_skill_id: 745
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 747
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 748
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 745
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 746
            }
          }
          children {
            behavior {
              enemy_skill_id: 745
            }
          }
        }
      }
    }
  }
  level_overrides {
    level: 1
    groups {
      group_type: PREEMPT
      condition {
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 744
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                  }
                  enemy_skill_id: 745
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 2
              }
              children {
                behavior {
                  condition {
                  }
                  enemy_skill_id: 747
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 3
              }
              children {
                behavior {
                  condition {
                  }
                  enemy_skill_id: 748
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
              }
              enemy_skill_id: 746
            }
          }
        }
      }
    }
  }
  status: APPROVED_WITH_CHANGES
